<script setup lang="ts">
import {
  Activity,
  BookOpen,
  Box,
  Boxes,
  Camera,
  Check,
  ChevronDown,
  ChevronRight,
  CircleCheck,
  Columns2,
  Crosshair,
  Dices,
  Download,
  Footprints,
  Gauge,
  Grid3x3,
  Hash,
  Info,
  Layers,
  LayoutGrid,
  ListOrdered,
  Maximize2,
  Monitor,
  Network,
  Package,
  Pause,
  Play,
  Rotate3d,
  Route,
  Ruler,
  Scale,
  ScanLine,
  Settings2,
  Shuffle,
  SkipBack,
  SkipForward,
  SlidersHorizontal,
  Sparkles,
  StepBack,
  StepForward,
  Target,
  Timer,
  TriangleAlert,
  Undo2,
  Upload,
  Weight,
  Workflow,
  X,
} from 'lucide-vue-next'
import type { Component } from 'vue'

withDefaults(defineProps<{ name: string; size?: number; stroke?: number }>(), { size: 16, stroke: 1.9 })

const MAP: Record<string, Component> = {
  play: Play,
  pause: Pause,
  prev: StepBack,
  next: StepForward,
  first: SkipBack,
  last: SkipForward,
  dice: Dices,
  upload: Upload,
  download: Download,
  info: Info,
  check: Check,
  checkCircle: CircleCheck,
  x: X,
  alert: TriangleAlert,
  spark: Sparkles,
  cube: Box,
  boxes: Boxes,
  layers: Layers,
  target: Crosshair,
  aim: Target,
  rotate: Rotate3d,
  hash: Hash,
  scale: Scale,
  compare: Columns2,
  station: Monitor,
  book: BookOpen,
  chevron: ChevronRight,
  chevronDown: ChevronDown,
  foot: Footprints,
  undo: Undo2,
  image: Camera,
  fullscreen: Maximize2,
  settings: Settings2,
  sliders: SlidersHorizontal,
  grid: LayoutGrid,
  grid3: Grid3x3,
  shuffle: Shuffle,
  gauge: Gauge,
  timer: Timer,
  package: Package,
  workflow: Workflow,
  scan: ScanLine,
  activity: Activity,
  weight: Weight,
  ruler: Ruler,
  route: Route,
  order: ListOrdered,
  network: Network,
}
</script>

<template>
  <component :is="MAP[name] ?? Box" :size="size" :stroke-width="stroke" aria-hidden="true" class="ic" />
</template>

<style scoped>
.ic {
  flex: none;
}
</style>
