<script setup lang="ts">
import {
  Activity,
  BookOpen,
  Box,
  Boxes,
  Camera,
  Check,
  ChevronDown,
  ChevronRight,
  CircleCheck,
  Columns2,
  Crosshair,
  Dices,
  Download,
  Footprints,
  Gauge,
  Grid3x3,
  Hash,
  Info,
  Layers,
  LayoutGrid,
  ListOrdered,
  Maximize2,
  Monitor,
  Network,
  Package,
  Pause,
  Play,
  Rotate3d,
  Route,
  Ruler,
  Scale,
  ScanLine,
  Settings2,
  Shuffle,
  SkipBack,
  SkipForward,
  SlidersHorizontal,
  Sparkles,
  StepBack,
  StepForward,
  Target,
  Timer,
  TriangleAlert,
  Undo2,
  Upload,
  Weight,
  Workflow,
  X,
  Database,
  CircleQuestionMark,
  LogOut,
  User,
  Plane,
  Warehouse,
  History,
  FileBraces,
  Plug,
  Save,
  Trash2,
  Pencil,
  RefreshCw,
  RotateCw,
  ArrowRight,
  ChevronLeft,
  Lock,
  Copy,
  Send,
  Server,
  ListChecks,
  Cpu,
  ArrowDownToLine,
  Split,
  PlaneTakeoff,
  PackageCheck,
  Eye,
  ArrowLeftRight,
  Zap,
  Link2,
  CircleAlert,
  FolderOpen,
  ShieldCheck,
  WandSparkles,
  DoorOpen,
  MousePointerClick,
  Truck,
  Container,
  PanelRightOpen,
  Move,
  Bot,
  Hand,
  Flame,
} from 'lucide-vue-next'
import type { Component } from 'vue'

withDefaults(defineProps<{ name: string; size?: number; stroke?: number }>(), { size: 16, stroke: 1.9 })

const MAP: Record<string, Component> = {
  play: Play,
  pause: Pause,
  prev: StepBack,
  next: StepForward,
  first: SkipBack,
  last: SkipForward,
  dice: Dices,
  upload: Upload,
  download: Download,
  info: Info,
  check: Check,
  checkCircle: CircleCheck,
  x: X,
  alert: TriangleAlert,
  spark: Sparkles,
  cube: Box,
  boxes: Boxes,
  layers: Layers,
  target: Crosshair,
  aim: Target,
  rotate: Rotate3d,
  hash: Hash,
  scale: Scale,
  compare: Columns2,
  station: Monitor,
  book: BookOpen,
  chevron: ChevronRight,
  chevronDown: ChevronDown,
  foot: Footprints,
  undo: Undo2,
  image: Camera,
  fullscreen: Maximize2,
  settings: Settings2,
  sliders: SlidersHorizontal,
  grid: LayoutGrid,
  grid3: Grid3x3,
  shuffle: Shuffle,
  gauge: Gauge,
  timer: Timer,
  package: Package,
  workflow: Workflow,
  scan: ScanLine,
  activity: Activity,
  weight: Weight,
  ruler: Ruler,
  route: Route,
  order: ListOrdered,
  network: Network,
  database: Database,
  help: CircleQuestionMark,
  logout: LogOut,
  user: User,
  plane: Plane,
  warehouse: Warehouse,
  history: History,
  json: FileBraces,
  plug: Plug,
  save: Save,
  trash: Trash2,
  pencil: Pencil,
  refresh: RefreshCw,
  rotateCw: RotateCw,
  arrowRight: ArrowRight,
  chevronLeft: ChevronLeft,
  lock: Lock,
  copy: Copy,
  send: Send,
  server: Server,
  checks: ListChecks,
  cpu: Cpu,
  drop: ArrowDownToLine,
  split: Split,
  takeoff: PlaneTakeoff,
  packageCheck: PackageCheck,
  eye: Eye,
  swap: ArrowLeftRight,
  zap: Zap,
  link: Link2,
  alertCircle: CircleAlert,
  folder: FolderOpen,
  shield: ShieldCheck,
  wand: WandSparkles,
  door: DoorOpen,
  click: MousePointerClick,
  truck: Truck,
  container: Container,
  panelRight: PanelRightOpen,
  move: Move,
  robot: Bot,
  hand: Hand,
  heat: Flame,
}
</script>

<template>
  <component :is="MAP[name] ?? Box" :size="size" :stroke-width="stroke" aria-hidden="true" class="ic" />
</template>

<style scoped>
.ic {
  flex: none;
}
</style>
